### ISSUE TITLE
Broken link: Advanced Coroutines with Kotlin Flow and LiveData

### ISSUE THREAD

**Issue by shervinkoushan** [googlecodelabs/kotlin-coroutines#143] opened 2021-06-13 09:03 UTC
The last step [here ](https://developer.android.com/codelabs/kotlin-coroutines#12) mentions another code lab, but the link is broken. The correct link seems to be: https://developer.android.com/codelabs/advanced-kotlin-coroutines#0

**Comment by osuleymanova** [comment] 2021-11-05 16:25
Duplicate of #141

**Comment by osuleymanova** [comment] 2021-11-10 18:20
@shervinkoushan 
Thank you for reaching out to us. The issue is fixed and published.

**Closed** 2023-01-19 11:51 UTC
