### ISSUE TITLE
Test not working

### ISSUE THREAD

**Issue by qazt482** [googlecodelabs/kotlin-coroutines#31] opened 2019-06-04 11:21 UTC
I am going through the tutorial and the final version of the MainViewModelTest with the TestCoroutineDispatcher does not work.

By not work, what I mean is, it always passes. My assert text is clearly wrong but it passes anyway. I even added a breakpoint to the body of the test and it never triggers.

I did notice a typo in the setup - dispatcher should be testDispatcher. Apart from this, and the different assert text, the test is the same as the website.

**Comment by manuelvicnt** [comment] 2019-06-04 14:07
Hi! Sorry but I don't understand what's the issue. Which tests do not pass? `MainViewModelUnitTest` or `MainViewModelTest`? I ran both locally and they both pass. Are you in the latest version of the repo?

**Comment by qazt482** [comment] 2019-06-04 14:14
`MainViewModelTest` with the TestDispatcher code. Break the test by changing the text to assert for - does it fail?

**Comment by manuelvicnt** [comment] 2019-06-04 14:30
Cannot reproduce the issue. Closing for now.

**Closed by manuelvicnt** 2019-06-04 14:30 UTC

**Comment by qazt482** [comment] 2019-06-04 14:52
Good point, I updated libraries. I'll try with the original ones.
